services:
  - type: web
    name: wedding-card
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: PYTHON_VERSION
        value: 3.11
    staticPublishPath: staticfiles
    