# Generated by Django 5.2.3 on 2025-07-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreetingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=50, verbose_name='اسم العريس')),
                ('bride_name', models.CharField(max_length=50, verbose_name='اسم العروسة')),
                ('slug', models.SlugField(unique=True, verbose_name='الاسم المختصر للرابط')),
                ('groom_image', models.ImageField(upload_to='groom_images/', verbose_name='صورة العريس')),
                ('bride_image', models.ImageField(upload_to='bride_images/', verbose_name='صورة العروسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'كارت تهنئة',
                'verbose_name_plural': 'كروت التهنئة',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص التهنئة')),
                ('sender_name', models.CharField(max_length=50, verbose_name='اسم المُرسل')),
                ('to', models.CharField(choices=[('groom', 'العريس'), ('bride', 'العروسة')], max_length=10, verbose_name='إلى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='greeting.greetingcard', verbose_name='كارت التهنئة')),
            ],
            options={
                'verbose_name': 'رسالة تهنئة',
                'verbose_name_plural': 'رسائل التهنئة',
            },
        ),
    ]
